#!/usr/bin/bash
# VSCode - Open git bash terminal, create a file pre-push in .git/hooks
# Paste this code in .git/hooks/pre-push and convert to executable file
# In sandbox open .git/hooks and create file pre-push and paste this code, after that covert this file to executable
# IMPORTANT!! check your name for main/master and change the value in branch_bloqued for each case

branch_blocked=main

if grep -q "$branch_blocked"; then
     echo "Branch '$branch_blocked' is blocked by yourself." >&2
     exit 1
fi
