# Generated by Django 2.2.12 on 2022-06-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=80, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(blank=True, max_length=10, null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('product_url', models.URLField(blank=True)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]