# Generated by Django 4.0.5 on 2022-06-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
                ('UrlImg', models.CharField(max_length=120)),
                ('Brand', models.CharField(max_length=120)),
                ('Slug', models.SlugField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('SuperMarketId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
                ('Address', models.CharField(max_length=120)),
                ('Phone', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMarket',
            fields=[
                ('ProductMarketId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductPrice', models.CharField(max_length=45)),
                ('UpdateAt', models.DateTimeField(auto_now=True)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('SuperMarketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supermarket')),
            ],
        ),
    ]
