# Generated by Django 4.0.5 on 2022-06-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
                ('UrlImg', models.CharField(max_length=120)),
                ('Brand', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SuperMarkets',
            fields=[
                ('SuperMarketId', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=120)),
                ('Url', models.CharField(max_length=120)),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductMarket',
            fields=[
                ('ProductMarketId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=120)),
                ('ProductPrice', models.IntegerField()),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('SuperMarketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supermarkets')),
            ],
        ),
    ]
