# Generated by Django 4.0.5 on 2022-06-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperMarkets',
            new_name='SuperMarket',
        ),
    ]
