# Generated by Django 4.0.5 on 2022-06-16 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_supermarkets_supermarket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmarket',
            name='ProductName',
        ),
        migrations.AddField(
            model_name='productmarket',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 19, 52, 6, 246690)),
        ),
        migrations.AlterField(
            model_name='productmarket',
            name='ProductPrice',
            field=models.CharField(max_length=45),
        ),
    ]
