# Generated by Django 4.0.5 on 2022-06-16 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_productmarket_updateat_alter_supermarket_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supermarket',
            old_name='Url',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='productmarket',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 20, 14, 32, 89635)),
        ),
    ]
