# Generated by Django 4.0.5 on 2022-06-16 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_url_supermarket_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmarket',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 20, 19, 31, 147675), null=True),
        ),
    ]
