# Generated by Django 4.0.5 on 2022-06-16 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_productmarket_updateat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supermarket',
            old_name='name',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='productmarket',
            name='UpdateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 20, 25, 38, 119266), null=True),
        ),
    ]
