# Generated by Django 4.0.5 on 2022-06-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_productmarket_updateat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmarket',
            name='UpdateAt',
            field=models.DateTimeField(),
        ),
    ]
