# Generated by Django 4.0.5 on 2022-06-12 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120)),
                ('product_price', models.IntegerField()),
                ('img', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=400)),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('phone', models.IntegerField()),
                ('url', models.CharField(max_length=120)),
                ('map', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.AddField(
            model_name='product',
            name='super_market_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supermarket'),
        ),
    ]
